# mkdocs build --clean
# mkdocs serve
#
# NOTE: to ensure extensions and plugins are installed be sure to re-source the `.venv` directory
# _AFTER_ installing the **requirements.txt**
#
# > `% pip install -r requirements.txt && source .venv/bin/activate && cd src && mkdocs build --clean`
#
site_name: DownQuark Doqumentation
site_author: DownQuark Development
site_description: Entropic Progress
use_directory_urls: false

docs_dir: ./_md
site_dir: ./dist

# extra: # keyvalue pairs passed directly to template
#   version: 1.0

# extra_css: # loads in `style` tags
#   - css/extra.css
#   - css/second_extra.css
#
# extra_javascript: # loads in `script` tags
#   - js/extra.js

# if _NOT_ defined, the `nav` key will auto-populate values from files in the `docs_dir`.
# - Below allows for editing, deleting any auto-genereated chages that are not desired
######

# nav:
#   - Home: index.md
#   - UX/UI:
#       - Overview: ui/index.md
#       - Scalable Development:
#           - Overview: ui/index.md
#           - Implementation:
#               - Implementation: ui/index.md
#   - CLI: cli/coming-soon.md
#   - WIP: # even though it's below specifeies the `_wip` directory should be ignored the nav setting has higher priority so they will be included
#       # warning will be displayed on build/serve if the `_wip` remains in the `nav`
#       - Overview: _wip/overview.md
#       - Scrx: _scrx/.gitkeep
#       - Store State Exploration:
#           - Overview: _wip/awesome-feature/overview.md

draft_docs: _wip/awesome-feature/details.md # omitted from build, included in serve
not_in_nav: | # exported, not included in menu
  _assets/*
  _wip

markdown_extensions:

plugins:
  - kroki:
      ServerURL: !ENV [KROKI_SERVER_URL, "https://kroki.io"]
      FencePrefix: "kroki-" # used to identify kroki diagrams in triple backtick code blocks

theme:
  name: mkdocs
  color_mode: dark
  highlightjs: true
  hljs_style_dark: shades-of-purple
  nav_style: dark
  navigation_depth: 13
  user_color_mode_toggle: true
